let strip = neopixel.create(DigitalPin.P1, 10, NeoPixelMode.RGB)
basic.showIcon(IconNames.Heart)
basic.forever(function () {
    strip.setPixelColor(3, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Black))
    strip.show()
    basic.pause(2000)
    strip.setPixelColor(3, neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Yellow))
    strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Black))
    strip.show()
    basic.pause(1000)
    strip.setPixelColor(3, neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Green))
    strip.show()
    basic.pause(2000)
})
